
class Cell:
	HORIZONTAL_WALL_SYMBOL = '-' 
	VERTICAL_WALL_SYMBOL = '|' 
	TOP_CORNER_SYMBOL = '-' 
	BOTTOM_CORNER_SYMBOL = '-' 
	EMPTY_SYMBOL = ' ' 
	FLOOR_SYMBOL = '.'
	DOOR_SYMBOL = '+'
	"""
	HORIZONTAL_WALL_SYMBOL = 'W' 
	VERTICAL_WALL_SYMBOL = 'W' 
	TOP_CORNER_SYMBOL = 'W' 
	BOTTOM_CORNER_SYMBOL = 'W' 
	EMPTY_SYMBOL = ' ' 
	FLOOR_SYMBOL = '.'
	DOOR_SYMBOL = '+'
	"""
	def __init__(self):
		self.ascii = Cell.EMPTY_SYMBOL
